### ISSUE TITLE
Failed to load imported SKOS ontology

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ontoportal/ontologies_linked_data#6]
Since the 24th of October,  the unit tests of this project are failing, 
```
Finished tests in 650.983909s, 0.2980 tests/s, 23.2479 assertions/s.

  1) Failure:
TestMapping#test_mappings_rest [/Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/models/test_mappings.rb:289]:
Expected: 3
  Actual: 4

  3) Failure:
TestOntologySubmission#test_submission_metrics [/Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/models/test_ontology_submission.rb:1027]:
Expected: 486
  Actual: 481

  4) Failure:
TestOntologySubmission#test_index_properties [/Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/models/test_ontology_submission.rb:424]:
Expected: 80
  Actual: 52
```

It seems to be because of an external change in the server responsible for dereferencing SKOS `http://www.w3.org/2004/02/skos/core`, OWLAPI can no longer import it into an ontology. 
```xml
 <owl:Ontology rdf:about="http://bioontology.org/ontologies/BiomedicalResources.owl">
        <owl:imports rdf:resource="http://www.w3.org/2004/02/skos/core"/>
    </owl:Ontology>
```

OWLAPI logs 

```
   INFO  15:42:18  ------------------------------- Loading Ontology -------------------------------
   INFO  15:42:18  Loading ontology from file:/Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/data/ontology_files/repo/BROTEST-METRICS/33/BRO_v3.2.owl
   INFO  15:42:18  Adding folder to ontology catalog: /Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/data/ontology_files/repo/BROTEST-METRICS/33
   INFO  15:42:18  ---------------------------- Starting Catalog Update ---------------------------
   INFO  15:42:18  Update of group entry Folder Repository, directory=, recursive=true, Auto-Update=true, version=2 started at Wed Oct 25 15:42:18 PDT 2023.
   INFO  15:42:18   Examining: /Users/vendetti/Development/GitHub/ncbo/ontologies_linked_data/test/data/ontology_files/repo/BROTEST-METRICS/33
   INFO  15:42:18  Catalog Update Complete
   INFO  15:42:18  
   INFO  15:42:18  Imported ontology document http://www.w3.org/2004/02/skos/core was not resolved to any documents defined in the ontology catalog.
   INFO  15:42:18  Failed to load imported ontology at http://www.w3.org/2004/02/skos/core
```
The SKOS server is returning an HTTP response code: 429 for the URL: https://www.w3.org/2004/02/skos/core, and it even occurs  if you try to load the vocabulary directly, rather than as an import: 
```java

IRI skosCoreIRI = IRI.create("http://www.w3.org/2004/02/skos/core");
OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
OWLOntology ontology = manager.loadOntology(skosCoreIRI);
```

**Comment by jvendetti** [comment]
I reached out to W3C support to ask if they've made any recent changes to how SKOS Core is served. I got this response:

>We recently adjusted our abuse prevention systems to address an 
excessive volume of requests from automated systems, adding up to 
tens of millions of requests per day.
>
>Do you have an idea of how frequently these requests are being 
made by your application? Our current system limits Java/* 
user-agents to 10 requests per minute per URI.
>
>If you are able to customize the user-agent header to identify 
your application on outgoing requests that should help bypass 
this generic restriction on Java user-agents. If it's making a 
large number of requests it would be good to add a cache as well.

They're rate limiting requests from all Java user agents. In thinking about how to address this issue, I wondered if using the OWL API's SimpleIRIMapper might be a solution. I've [filed a question](https://github.com/owlcs/owlapi/issues/1114) with the OWL API developers to ask their advice on this matter.

**Comment by alexskr** [comment]
unit tests started to work for me today, perhaps W3C adjusted throttling on their end.  Nevertheless, caching frequently accessed and infrequently updated imports would be the right approach.

**Comment by syphax-bouazzouni** [comment]
> unit tests started to work for me today, perhaps W3C adjusted throttling on their end. Nevertheless, caching/setting up IRI mapper for frequently accessed and infrequently updated imports would be the right approach.

It randomly sometimes works, if we don't atteint their threshold 
![image](https://github.com/ontoportal/ontologies_linked_data/assets/29259906/9588d8a6-5ad6-4d37-aff9-6a033d80cdc9)

**Comment by syphax-bouazzouni** [comment]
Fixed by https://github.com/ontoportal/owlapi_wrapper/pull/1
